previews:
  generation: automatic

services:
  - type: web
    runtime: nodejs
    name: my_webapp
    repo: https://github.com/yahia-adam/cloud_static_app
    # region: frankfurt
    # plan: standard    # Default: starter
    branch: main      # Default: master
    buildCommand: npm install
    
